# version: '3.8'

services:
  nestapp:
    build: ./
    ports:
      - "3001:3000"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: